# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20190902_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuprequest',
            name='due_date',
            field=models.DateField(help_text=b'MM/DD/YYYY'),
        ),
    ]
