# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-10 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
    ]
