# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pttrack', '0010_auto_20200524_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscreteResultType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('long_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('unit', models.CharField(blank=True, max_length=15)),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.LabType')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labs.Measurement')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            bases=('labs.measurement',),
        ),
        migrations.CreateModel(
            name='DiscreteMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labs.Measurement')),
            ],
            bases=('labs.measurement',),
        ),
        migrations.AddField(
            model_name='measurement',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Lab'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.MeasurementType'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.LabType'),
        ),
        migrations.AddField(
            model_name='lab',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pttrack.Patient'),
        ),
        migrations.AddField(
            model_name='discreteresulttype',
            name='measurement_type',
            field=models.ManyToManyField(to='labs.MeasurementType'),
        ),
        migrations.AddField(
            model_name='discretemeasurement',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.DiscreteResultType'),
        ),
    ]
